---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sh installer.sh

vscode:
  extensions:
    - mhutchie.git-graph
    - esbenp.prettier-vscode
    - ritwickdey.LiveServer
    - dbaeumer.vscode-eslint
